# Changes here will be overwritten by Copier
_commit: 2.6.0
_src_path: gh:DiamondLightSource/python-copier-template
author_email: zoheb.shaikh@diamond.ac.uk
author_name: Zoheb Shaikh
description: Contains algorithms practice area
distribution_name: kata-repo
docker: true
docs_type: README
git_platform: github.com
github_org: ZohebShaikh
package_name: kata_repo
pypi: false
repo_name: kata-repo
type_checker: pyright
