# Changes here will be overwritten by Copier
_commit: 5.0.1
_src_path: gh:DiamondLightSource/python-copier-template
author_email: zoheb.shaikh@diamond.ac.uk
author_name: Zoheb Shaikh
description: Contains algorithms practice area
distribution_name: kata-repo
docker: false
docs_type: README
git_platform: github.com
github_org: ZohebShaikh
package_name: kata_repo
pypi: false
repo_name: kata-repo
strict_typing: true
type_checker: pyright
